// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TourOfHeroes_Backend.DataContext;

#nullable disable

namespace TourOfHeroesBackend.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TourOfHeroes_Backend.Models.Hero", b =>
                {
                    b.Property<int>("HeroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HeroId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HeroId");

                    b.ToTable("Heroes");

                    b.HasData(
                        new
                        {
                            HeroId = 1,
                            Name = "Spiderman"
                        },
                        new
                        {
                            HeroId = 2,
                            Name = "Superman"
                        },
                        new
                        {
                            HeroId = 3,
                            Name = "Ironman"
                        },
                        new
                        {
                            HeroId = 4,
                            Name = "Electra"
                        },
                        new
                        {
                            HeroId = 5,
                            Name = "Catwoman"
                        },
                        new
                        {
                            HeroId = 6,
                            Name = "Thor"
                        },
                        new
                        {
                            HeroId = 7,
                            Name = "Hulk"
                        },
                        new
                        {
                            HeroId = 8,
                            Name = "Robin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
